# Generated by Django 5.2.12 on 2026-04-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank_accounts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
