# Generated by Django 5.2.12 on 2026-04-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu_app', '0003_profile_national_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='national_id',
            new_name='bvn',
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='nin',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
