# Generated by Django 5.2.12 on 2026-04-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu_app', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('01', 'MTN'), ('02', 'Glo'), ('03', '9mobile'), ('04', 'Airtel')], max_length=2)),
                ('plan_name', models.CharField(max_length=100)),
                ('dataplan_id', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
