# Generated by Django 5.2.12 on 2026-04-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu_app', '0006_dataplan_transaction_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CablePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_type', models.CharField(choices=[('dstv', 'DStv'), ('gotv', 'GOtv'), ('startimes', 'StarTimes')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('package_code', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
