# Generated by Django 5.2.12 on 2026-04-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu_app', '0007_cableplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_pin_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='transaction_pin',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
