# Generated by Django 5.2.12 on 2026-04-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu_app', '0009_alter_profile_transaction_pin_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableplan',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dataplan',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service_type',
            field=models.CharField(choices=[('Wallet Funding', 'Wallet Funding'), ('Data Purchase', 'Data Purchase'), ('Airtime Purchase', 'Airtime Purchase'), ('Cable TV', 'Cable TV')], max_length=50),
        ),
    ]
