# Generated by Django 5.2.12 on 2026-04-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu_app', '0010_cableplan_cost_price_dataplan_cost_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('MTN', 'MTN'), ('Glo', 'Glo'), ('9mobile', '9mobile'), ('Airtel', 'Airtel')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
