# Generated by Django 4.2.7 on 2026-04-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu_app', '0011_serviceswitch_transaction_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
