# Generated by Django 4.2.7 on 2026-04-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu_app', '0012_transaction_net_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='selling_price',
            new_name='amount_customer_paid',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='fee',
            new_name='bt_service_charge',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='net_amount',
            new_name='cost_from_klubconnect',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='profit',
        ),
        migrations.AddField(
            model_name='cableplan',
            name='additional_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dataplan',
            name='additional_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='monnify_fee_on_this_tx',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
