# Generated by BT DataPlug AI to fix production migration errors
from django.db import migrations
import uuid

def generate_unique_codes(apps, schema_editor):
    Profile = apps.get_model('vtu_app', 'Profile')
    for profile in Profile.objects.filter(referral_code=''):
        profile.referral_code = f"BT-{uuid.uuid4().hex[:6].upper()}"
        profile.save()

def reverse_code_generation(apps, schema_editor):
    pass # No need to clear codes on reverse

class Migration(migrations.Migration):

    dependencies = [
        ('vtu_app', '0014_profile_referral_code_profile_referred_by'),
    ]

    operations = [
        migrations.RunPython(generate_unique_codes, reverse_code_generation),
    ]
