# Generated by Django 4.2.7 on 2026-04-15 13:32

from django.db import migrations


def reset_pins(apps, schema_editor):
    from django.contrib.auth.hashers import make_password
    Profile = apps.get_model('vtu_app', 'Profile')
    hashed_pin = make_password('0000')
    Profile.objects.all().update(transaction_pin=hashed_pin, is_pin_set=True)

def reverse_reset(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('vtu_app', '0016_alter_profile_referral_code'),
    ]

    operations = [
        migrations.RunPython(reset_pins, reverse_reset),
    ]
