# Generated by Django 4.2.7 on 2026-04-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtu_app', '0017_reset_all_pins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cableplan',
            old_name='package_code',
            new_name='plan_id',
        ),
    ]
