# Generated by Django 4.2.7 on 2026-04-16 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vtu_app', '0018_rename_package_code_cableplan_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='service_type',
            field=models.CharField(choices=[('Wallet Funding', 'Wallet Funding'), ('Data Purchase', 'Data Purchase'), ('Airtime Purchase', 'Airtime Purchase'), ('Cable TV', 'Cable TV'), ('Electricity Bill', 'Electricity Bill')], max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
