# Generated by Django 5.2.12 on 2026-08-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtu_app', '0019_alter_transaction_service_type_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
